# Generated by Django 3.0.7 on 2020-06-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_picture',
            field=models.ImageField(default='dp/None/no-img.png', upload_to='dp/'),
        ),
    ]
